# Generated by Django 5.1.15 on 2026-02-24 11:19

import django.utils.timezone
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GBPConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('place_id', models.CharField(max_length=255)),
                ('business_name', models.CharField(max_length=255)),
                ('access_token', models.TextField(blank=True)),
                ('refresh_token', models.TextField(blank=True)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'gbp_connections',
            },
        ),
        migrations.CreateModel(
            name='KBChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('chunk_index', models.IntegerField(default=0)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True)),
                ('token_count', models.IntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'kb_chunks',
                'ordering': ['chunk_index'],
            },
        ),
        migrations.CreateModel(
            name='KBConflict',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('detected', 'Detected'), ('resolved', 'Resolved'), ('ignored', 'Ignored')], default='detected', max_length=50)),
                ('resolution', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'kb_conflicts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KBDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('source_type', models.CharField(choices=[('upload', 'File Upload'), ('url', 'URL Scrape'), ('text', 'Manual Text'), ('gbp', 'Google Business Profile'), ('faq', 'Auto-Generated FAQ')], default='upload', max_length=50)),
                ('source_url', models.URLField(blank=True)),
                ('file_url', models.URLField(blank=True)),
                ('file_type', models.CharField(blank=True, max_length=50)),
                ('raw_text', models.TextField(blank=True)),
                ('extracted_text', models.TextField(blank=True)),
                ('user_edited', models.BooleanField(default=False)),
                ('chunk_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=50)),
                ('processing_progress', models.IntegerField(default=0)),
                ('processing_step', models.CharField(blank=True, max_length=100)),
                ('error_message', models.TextField(blank=True)),
                ('is_stale', models.BooleanField(default=False)),
                ('stale_reason', models.CharField(blank=True, max_length=255)),
                ('last_verified', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'kb_documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KBFaq',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('category', models.CharField(blank=True, max_length=100)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('is_auto_generated', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'kb_faqs',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='KBScrapeSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='weekly', max_length=50)),
                ('last_scraped', models.DateTimeField(blank=True, null=True)),
                ('next_scrape', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'kb_scrape_schedules',
            },
        ),
        migrations.CreateModel(
            name='KBSearchLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('query', models.TextField()),
                ('results_count', models.IntegerField(default=0)),
                ('top_result_score', models.FloatField(blank=True, null=True)),
                ('was_helpful', models.BooleanField(blank=True, null=True)),
                ('source', models.CharField(default='dashboard', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'kb_search_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
