# Generated by Django 5.1.15 on 2026-02-24 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kb', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gbpconnection',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gbp_connections', to='users.organization'),
        ),
        migrations.AddField(
            model_name='kbconflict',
            name='chunk_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts_as_a', to='kb.kbchunk'),
        ),
        migrations.AddField(
            model_name='kbconflict',
            name='chunk_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts_as_b', to='kb.kbchunk'),
        ),
        migrations.AddField(
            model_name='kbconflict',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kb_conflicts', to='users.organization'),
        ),
        migrations.AddField(
            model_name='kbconflict',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kbdocument',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kb_documents', to='users.organization'),
        ),
        migrations.AddField(
            model_name='kbchunk',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='kb.kbdocument'),
        ),
        migrations.AddField(
            model_name='kbfaq',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kb_faqs', to='users.organization'),
        ),
        migrations.AddField(
            model_name='kbfaq',
            name='source_chunks',
            field=models.ManyToManyField(blank=True, related_name='faqs', to='kb.kbchunk'),
        ),
        migrations.AddField(
            model_name='kbscrapeschedule',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrape_schedules', to='users.organization'),
        ),
        migrations.AddField(
            model_name='kbsearchlog',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kb_search_logs', to='users.organization'),
        ),
    ]
