# Generated by Django 5.1.15 on 2026-02-24 12:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('visitor_id', models.CharField(blank=True, default='', max_length=255)),
                ('visitor_name', models.CharField(blank=True, default='', max_length=255)),
                ('visitor_email', models.EmailField(blank=True, default='', max_length=254)),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('transferred', 'Transferred to Human')], default='active', max_length=20)),
                ('channel', models.CharField(choices=[('web', 'Web Chat'), ('sms', 'SMS')], default='web', max_length=20)),
                ('sentiment_score', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('actions_taken', models.JSONField(blank=True, default=list)),
                ('source_url', models.URLField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to='users.organization')),
            ],
            options={
                'db_table': 'chat_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('visitor', 'Visitor'), ('assistant', 'Assistant'), ('system', 'System')], max_length=20)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='receptionist.chatsession')),
            ],
            options={
                'db_table': 'chat_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReceptionistConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=False)),
                ('persona_name', models.CharField(default='Assistant', max_length=100)),
                ('greeting_message', models.TextField(default='Hello! How can I help you today?')),
                ('avatar_url', models.URLField(blank=True, default='')),
                ('primary_color', models.CharField(default='#2563EB', max_length=7)),
                ('position', models.CharField(choices=[('bottom-right', 'Bottom Right'), ('bottom-left', 'Bottom Left')], default='bottom-right', max_length=20)),
                ('business_hours', models.JSONField(blank=True, default=dict)),
                ('after_hours_message', models.TextField(default="We're currently closed. Please leave a message and we'll get back to you.")),
                ('language', models.CharField(default='en', max_length=10)),
                ('max_ai_turns', models.IntegerField(default=10)),
                ('escalation_keywords', models.JSONField(blank=True, default=list, help_text='Keywords that trigger human handoff, e.g. ["emergency", "urgent"]')),
                ('custom_instructions', models.TextField(blank=True, default='', help_text='Additional instructions for the AI receptionist persona.')),
                ('can_book_appointments', models.BooleanField(default=True)),
                ('can_collect_leads', models.BooleanField(default=True)),
                ('can_answer_faq', models.BooleanField(default=True)),
                ('embed_key', models.CharField(editable=False, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('org', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receptionist_config', to='users.organization')),
            ],
            options={
                'db_table': 'receptionist_configs',
            },
        ),
        migrations.CreateModel(
            name='ChatAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('total_sessions', models.IntegerField(default=0)),
                ('ai_resolved', models.IntegerField(default=0)),
                ('transferred', models.IntegerField(default=0)),
                ('leads_collected', models.IntegerField(default=0)),
                ('appointments_booked', models.IntegerField(default=0)),
                ('avg_messages_per_session', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('avg_sentiment', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('top_queries', models.JSONField(blank=True, default=list)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_analytics', to='users.organization')),
            ],
            options={
                'db_table': 'chat_analytics',
                'ordering': ['-date'],
                'unique_together': {('org', 'date')},
            },
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['org', '-created_at'], name='chat_sessio_org_id_71f98e_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['status'], name='chat_sessio_status_f6889c_idx'),
        ),
    ]
