# Generated by Django 5.1.15 on 2026-02-24 11:19

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ABTest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('running', 'Running'), ('paused', 'Paused'), ('completed', 'Completed')], default='draft', max_length=50)),
                ('traffic_split', models.JSONField(default=dict)),
                ('target_metric', models.CharField(default='conversion', max_length=100)),
                ('min_sample_size', models.IntegerField(default=100)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'ab_tests',
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('author_name', models.CharField(blank=True, max_length=255)),
                ('excerpt', models.TextField(blank=True)),
                ('featured_image_url', models.URLField(blank=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_featured', models.BooleanField(default=False)),
                ('reading_time_minutes', models.IntegerField(default=0)),
                ('allow_comments', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'blog_posts',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('category', models.CharField(max_length=100)),
                ('schema', models.JSONField(default=dict)),
                ('default_props', models.JSONField(default=dict)),
                ('preview_image_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'components',
            },
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('fields_schema', models.JSONField(default=list)),
                ('is_multi_step', models.BooleanField(default=False)),
                ('steps', models.JSONField(blank=True, default=list)),
                ('conditional_logic', models.JSONField(blank=True, default=list)),
                ('redirect_url', models.URLField(blank=True)),
                ('success_message', models.TextField(default='Thank you for your submission!')),
                ('notify_email', models.EmailField(blank=True, max_length=254)),
                ('honeypot_enabled', models.BooleanField(default=True)),
                ('recaptcha_enabled', models.BooleanField(default=False)),
                ('webhook_url', models.URLField(blank=True)),
                ('webhook_headers', models.JSONField(blank=True, default=dict)),
                ('allow_file_upload', models.BooleanField(default=False)),
                ('max_file_size_mb', models.IntegerField(default=10)),
                ('allowed_file_types', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('submission_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'forms',
            },
        ),
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'form_submissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MediaLibrary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('file_url', models.URLField()),
                ('file_type', models.CharField(max_length=50)),
                ('mime_type', models.CharField(max_length=100)),
                ('file_size', models.BigIntegerField()),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('alt_text', models.CharField(blank=True, max_length=500)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Media library',
                'db_table': 'media_library',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('path', models.CharField(max_length=500)),
                ('page_type', models.CharField(choices=[('page', 'Standard Page'), ('blog_post', 'Blog Post'), ('landing', 'Landing Page'), ('legal', 'Legal Page'), ('utility', 'Utility Page')], default='page', max_length=50)),
                ('is_homepage', models.BooleanField(default=False)),
                ('content_blocks', models.JSONField(default=list)),
                ('seo_title', models.CharField(blank=True, max_length=255)),
                ('seo_description', models.TextField(blank=True)),
                ('og_image_url', models.URLField(blank=True)),
                ('canonical_url', models.URLField(blank=True)),
                ('no_index', models.BooleanField(default=False)),
                ('schema_markup', models.JSONField(blank=True, default=dict)),
                ('custom_css', models.TextField(blank=True)),
                ('custom_js', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('scheduled', 'Scheduled')], default='draft', max_length=50)),
                ('publish_at', models.DateTimeField(blank=True, null=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('view_count', models.IntegerField(default=0)),
                ('unique_visitor_count', models.IntegerField(default=0)),
                ('avg_time_on_page', models.IntegerField(default=0)),
                ('bounce_rate', models.FloatField(default=0)),
                ('performance_score', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'pages',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='PageVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('content_blocks', models.JSONField(default=list)),
                ('diff_summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'page_versions',
                'ordering': ['-version_number'],
            },
        ),
        migrations.CreateModel(
            name='Popup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('trigger_type', models.CharField(choices=[('exit_intent', 'Exit Intent'), ('timed', 'Time Delay'), ('scroll', 'Scroll Percentage'), ('click', 'Click Trigger'), ('page_load', 'Page Load')], default='timed', max_length=50)),
                ('trigger_config', models.JSONField(default=dict)),
                ('content_blocks', models.JSONField(default=list)),
                ('target_pages', models.JSONField(blank=True, default=list)),
                ('frequency', models.CharField(choices=[('every_visit', 'Every Visit'), ('once_per_session', 'Once Per Session'), ('once_ever', 'Once Ever')], default='once_per_session', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('impressions', models.IntegerField(default=0)),
                ('conversions', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'popups',
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('custom_domain', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=50)),
                ('global_styles', models.JSONField(blank=True, default=dict)),
                ('seo_defaults', models.JSONField(blank=True, default=dict)),
                ('favicon_url', models.URLField(blank=True)),
                ('analytics_id', models.CharField(blank=True, max_length=100)),
                ('head_code', models.TextField(blank=True)),
                ('body_start_code', models.TextField(blank=True)),
                ('body_end_code', models.TextField(blank=True)),
                ('is_pwa', models.BooleanField(default=False)),
                ('pwa_manifest', models.JSONField(blank=True, default=dict)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sites',
            },
        ),
        migrations.CreateModel(
            name='SiteBackup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('backup_url', models.URLField()),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('pages_count', models.IntegerField(default=0)),
                ('backup_type', models.CharField(choices=[('auto', 'Automatic'), ('manual', 'Manual'), ('pre_deploy', 'Pre-Deploy')], default='auto', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'site_backups',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteNavigation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('location', models.CharField(choices=[('header', 'Header'), ('footer', 'Footer'), ('sidebar', 'Sidebar')], max_length=50)),
                ('items', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'site_navigation',
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('category', models.CharField(choices=[('hvac', 'HVAC'), ('restaurant', 'Restaurant'), ('yoga', 'Yoga / Fitness'), ('salon', 'Salon / Spa'), ('dental', 'Dental'), ('plumbing', 'Plumbing'), ('legal', 'Legal'), ('real_estate', 'Real Estate'), ('photography', 'Photography'), ('cleaning', 'Cleaning'), ('general', 'General')], default='general', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('preview_image_url', models.URLField(blank=True)),
                ('preview_url', models.URLField(blank=True)),
                ('default_pages', models.JSONField(default=list)),
                ('default_styles', models.JSONField(blank=True, default=dict)),
                ('is_premium', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('usage_count', models.IntegerField(default=0)),
                ('avg_rating', models.FloatField(default=0)),
                ('rating_count', models.IntegerField(default=0)),
                ('conversion_rate', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'templates',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='TemplateRating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('review', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'template_ratings',
            },
        ),
        migrations.CreateModel(
            name='ABTestVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('content_blocks', models.JSONField(default=list)),
                ('impressions', models.IntegerField(default=0)),
                ('conversions', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='site_builder.abtest')),
            ],
            options={
                'db_table': 'ab_test_variants',
            },
        ),
        migrations.AddField(
            model_name='abtest',
            name='winning_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_tests', to='site_builder.abtestvariant'),
        ),
    ]
