# Generated by Django 5.1.15 on 2026-02-24 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('site_builder', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='site_builder.form'),
        ),
        migrations.AddField(
            model_name='medialibrary',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medialibrary',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='users.organization'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='page',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='blog_post', to='site_builder.page'),
        ),
        migrations.AddField(
            model_name='abtest',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ab_tests', to='site_builder.page'),
        ),
        migrations.AddField(
            model_name='pageversion',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pageversion',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='site_builder.page'),
        ),
        migrations.AddField(
            model_name='site',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='users.organization'),
        ),
        migrations.AddField(
            model_name='popup',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='popups', to='site_builder.site'),
        ),
        migrations.AddField(
            model_name='page',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='site_builder.site'),
        ),
        migrations.AddField(
            model_name='form',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='site_builder.site'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to='site_builder.site'),
        ),
        migrations.AddField(
            model_name='sitebackup',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sitebackup',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backups', to='site_builder.site'),
        ),
        migrations.AddField(
            model_name='sitenavigation',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='navigation', to='site_builder.site'),
        ),
        migrations.AddField(
            model_name='site',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='site_builder.template'),
        ),
        migrations.AddField(
            model_name='templaterating',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='site_builder.template'),
        ),
        migrations.AddField(
            model_name='templaterating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='pageversion',
            unique_together={('page', 'version_number')},
        ),
        migrations.AlterUniqueTogether(
            name='page',
            unique_together={('site', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='sitenavigation',
            unique_together={('site', 'location')},
        ),
        migrations.AlterUniqueTogether(
            name='site',
            unique_together={('org', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='templaterating',
            unique_together={('template', 'user')},
        ),
    ]
