# Generated by Django 5.1.15 on 2026-02-24 11:19

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentApprovalQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(max_length=100)),
                ('action_description', models.TextField()),
                ('action_data', models.JSONField(default=dict)),
                ('preview_data', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=50)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'agent_approval_queue',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_name', models.CharField(default='AI Assistant', max_length=255)),
                ('persona', models.TextField(default='You are a helpful business assistant. Be friendly, professional, and concise.')),
                ('tone', models.CharField(choices=[('professional', 'Professional'), ('friendly', 'Friendly'), ('casual', 'Casual'), ('formal', 'Formal')], default='friendly', max_length=50)),
                ('enabled_tools', models.JSONField(blank=True, default=list)),
                ('llm_provider', models.CharField(default='openai', max_length=50)),
                ('llm_model', models.CharField(default='gpt-4o', max_length=100)),
                ('fallback_provider', models.CharField(default='claude', max_length=50)),
                ('fallback_model', models.CharField(default='claude-4.6', max_length=100)),
                ('design_provider', models.CharField(default='claude', max_length=50)),
                ('design_model', models.CharField(default='claude-4.6', max_length=100)),
                ('temperature', models.FloatField(default=0.7)),
                ('max_tokens', models.IntegerField(default=4096)),
                ('knowledge_base_enabled', models.BooleanField(default=True)),
                ('token_budget_daily', models.IntegerField(default=100000)),
                ('token_budget_monthly', models.IntegerField(default=2000000)),
                ('tokens_used_today', models.IntegerField(default=0)),
                ('tokens_used_month', models.IntegerField(default=0)),
                ('confidence_threshold', models.FloatField(default=0.7)),
                ('auto_approve_actions', models.BooleanField(default=False)),
                ('debug_mode', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'agent_configs',
            },
        ),
        migrations.CreateModel(
            name='AgentLearning',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=100)),
                ('original_output', models.TextField()),
                ('corrected_output', models.TextField()),
                ('user_feedback', models.TextField(blank=True)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'agent_learnings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='New Conversation', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('summary', models.TextField(blank=True)),
                ('total_tokens', models.IntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'conversations',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ConversationStateSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state_data', models.JSONField(default=dict)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'conversation_state_snapshots',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System'), ('tool', 'Tool')], max_length=20)),
                ('content', models.TextField()),
                ('tool_name', models.CharField(blank=True, max_length=100)),
                ('tool_args', models.JSONField(blank=True, default=dict)),
                ('tool_result', models.JSONField(blank=True, default=dict)),
                ('token_count', models.IntegerField(default=0)),
                ('model_used', models.CharField(blank=True, max_length=100)),
                ('latency_ms', models.IntegerField(default=0)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('is_undone', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromptCache',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cache_key', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('token_count', models.IntegerField(default=0)),
                ('hit_count', models.IntegerField(default=0)),
                ('last_used', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'prompt_cache',
            },
        ),
        migrations.CreateModel(
            name='ScheduledTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tool_name', models.CharField(max_length=100)),
                ('tool_args', models.JSONField(default=dict)),
                ('description', models.TextField(blank=True)),
                ('scheduled_for', models.DateTimeField()),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurrence_rule', models.CharField(blank=True, max_length=255)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('run_count', models.IntegerField(default=0)),
                ('max_runs', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=50)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'scheduled_tasks',
                'ordering': ['scheduled_for'],
            },
        ),
        migrations.CreateModel(
            name='ToolVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('parameters_schema', models.JSONField(default=dict)),
                ('return_schema', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('deprecated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'tool_versions',
                'ordering': ['name', '-version'],
            },
        ),
    ]
