# Generated by Django 5.1.15 on 2026-02-24 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agent', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agentapprovalqueue',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_queue', to='users.organization'),
        ),
        migrations.AddField(
            model_name='agentapprovalqueue',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agentconfig',
            name='org',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_config', to='users.organization'),
        ),
        migrations.AddField(
            model_name='agentlearning',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_learnings', to='users.organization'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='users.organization'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agentapprovalqueue',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='agent.conversation'),
        ),
        migrations.AddField(
            model_name='conversationstatesnapshot',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='agent.conversation'),
        ),
        migrations.AddField(
            model_name='message',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='agent.conversation'),
        ),
        migrations.AddField(
            model_name='message',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branches', to='agent.message'),
        ),
        migrations.AddField(
            model_name='conversationstatesnapshot',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshot', to='agent.message'),
        ),
        migrations.AddField(
            model_name='promptcache',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompt_cache', to='users.organization'),
        ),
        migrations.AddField(
            model_name='scheduledtask',
            name='conversation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_tasks', to='agent.conversation'),
        ),
        migrations.AddField(
            model_name='scheduledtask',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_tasks', to='users.organization'),
        ),
        migrations.AddField(
            model_name='scheduledtask',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='toolversion',
            unique_together={('name', 'version')},
        ),
        migrations.AlterUniqueTogether(
            name='promptcache',
            unique_together={('org', 'cache_key')},
        ),
    ]
