# Generated by Django 5.1.15 on 2026-02-24 11:19

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Automation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('trigger_type', models.CharField(max_length=100)),
                ('trigger_config', models.JSONField(blank=True, default=dict)),
                ('steps', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=False)),
                ('enrolled_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'automations',
            },
        ),
        migrations.CreateModel(
            name='AutomationEnrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_step', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('paused', 'Paused'), ('cancelled', 'Cancelled')], default='active', max_length=50)),
                ('next_action_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'automation_enrollments',
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=500)),
                ('from_name', models.CharField(max_length=255)),
                ('from_email', models.EmailField(max_length=254)),
                ('reply_to', models.EmailField(blank=True, max_length=254)),
                ('html_content', models.TextField()),
                ('text_content', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sending', 'Sending'), ('sent', 'Sent'), ('cancelled', 'Cancelled')], default='draft', max_length=50)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('total_sent', models.IntegerField(default=0)),
                ('total_delivered', models.IntegerField(default=0)),
                ('total_opens', models.IntegerField(default=0)),
                ('total_clicks', models.IntegerField(default=0)),
                ('total_bounces', models.IntegerField(default=0)),
                ('total_complaints', models.IntegerField(default=0)),
                ('total_unsubscribes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('opened', 'Opened'), ('clicked', 'Clicked'), ('bounced', 'Bounced'), ('complained', 'Complained'), ('unsubscribed', 'Unsubscribed')], max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'campaign_events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('company', models.CharField(blank=True, max_length=255)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('form', 'Form Submission'), ('import', 'CSV Import'), ('agent', 'AI Agent'), ('booking', 'Booking'), ('purchase', 'Purchase')], default='manual', max_length=50)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('custom_fields', models.JSONField(blank=True, default=dict)),
                ('lead_score', models.IntegerField(default=0)),
                ('is_subscribed', models.BooleanField(default=True)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
                ('last_activity', models.DateTimeField(blank=True, null=True)),
                ('lifecycle_stage', models.CharField(choices=[('subscriber', 'Subscriber'), ('lead', 'Lead'), ('marketing_qualified', 'Marketing Qualified'), ('sales_qualified', 'Sales Qualified'), ('opportunity', 'Opportunity'), ('customer', 'Customer'), ('evangelist', 'Evangelist')], default='subscriber', max_length=50)),
                ('sms_subscribed', models.BooleanField(default=False)),
                ('sms_phone', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'contacts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('email_sent', 'Email Sent'), ('email_opened', 'Email Opened'), ('email_clicked', 'Email Clicked'), ('form_submitted', 'Form Submitted'), ('page_visited', 'Page Visited'), ('booking_made', 'Booking Made'), ('purchase', 'Purchase Made'), ('call', 'Phone Call'), ('sms_sent', 'SMS Sent'), ('sms_received', 'SMS Received'), ('note', 'Manual Note'), ('tag_added', 'Tag Added'), ('deal_stage_changed', 'Deal Stage Changed'), ('enrolled', 'Enrolled in Course')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'contact_activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('stage', models.CharField(choices=[('lead', 'Lead'), ('qualified', 'Qualified'), ('proposal', 'Proposal'), ('negotiation', 'Negotiation'), ('won', 'Won'), ('lost', 'Lost')], default='lead', max_length=50)),
                ('probability', models.IntegerField(default=0)),
                ('expected_close_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'deals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliverabilityMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('emails_sent', models.IntegerField(default=0)),
                ('delivered', models.IntegerField(default=0)),
                ('bounced', models.IntegerField(default=0)),
                ('complaints', models.IntegerField(default=0)),
                ('bounce_rate', models.FloatField(default=0)),
                ('complaint_rate', models.FloatField(default=0)),
                ('reputation_score', models.IntegerField(default=100)),
                ('is_warming', models.BooleanField(default=False)),
                ('warmup_day', models.IntegerField(default=0)),
                ('daily_limit', models.IntegerField(default=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'deliverability_metrics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='EmailABTest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('test_type', models.CharField(choices=[('subject', 'Subject Line'), ('content', 'Content'), ('send_time', 'Send Time')], max_length=50)),
                ('variant_a', models.JSONField(default=dict)),
                ('variant_b', models.JSONField(default=dict)),
                ('sample_size_pct', models.IntegerField(default=20)),
                ('winning_metric', models.CharField(default='open_rate', max_length=50)),
                ('winner', models.CharField(blank=True, max_length=1)),
                ('results_a', models.JSONField(blank=True, default=dict)),
                ('results_b', models.JSONField(blank=True, default=dict)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'email_ab_tests',
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=500)),
                ('html_content', models.TextField()),
                ('text_content', models.TextField(blank=True)),
                ('variables', models.JSONField(blank=True, default=list)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'email_templates',
            },
        ),
        migrations.CreateModel(
            name='ScoringRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('event_type', models.CharField(max_length=100)),
                ('condition', models.JSONField(blank=True, default=dict)),
                ('points', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'scoring_rules',
            },
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_dynamic', models.BooleanField(default=True)),
                ('filter_rules', models.JSONField(blank=True, default=list)),
                ('contact_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'segments',
            },
        ),
        migrations.CreateModel(
            name='SMSCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('message', models.TextField(max_length=1600)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sending', 'Sending'), ('sent', 'Sent')], default='draft', max_length=50)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('total_sent', models.IntegerField(default=0)),
                ('total_delivered', models.IntegerField(default=0)),
                ('total_failed', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'sms_campaigns',
                'ordering': ['-created_at'],
            },
        ),
    ]
