# Generated by Django 5.1.15 on 2026-02-24 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('email_crm', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='automation',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automations', to='users.organization'),
        ),
        migrations.AddField(
            model_name='automationenrollment',
            name='automation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='email_crm.automation'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='users.organization'),
        ),
        migrations.AddField(
            model_name='campaignevent',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='email_crm.campaign'),
        ),
        migrations.AddField(
            model_name='contact',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='users.organization'),
        ),
        migrations.AddField(
            model_name='campaignevent',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_events', to='email_crm.contact'),
        ),
        migrations.AddField(
            model_name='automationenrollment',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automations', to='email_crm.contact'),
        ),
        migrations.AddField(
            model_name='contactactivity',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='email_crm.contact'),
        ),
        migrations.AddField(
            model_name='deal',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deal',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='email_crm.contact'),
        ),
        migrations.AddField(
            model_name='deal',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='users.organization'),
        ),
        migrations.AddField(
            model_name='deliverabilitymetrics',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverability_metrics', to='users.organization'),
        ),
        migrations.AddField(
            model_name='emailabtest',
            name='campaign',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ab_test', to='email_crm.campaign'),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_templates', to='users.organization'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='email_crm.emailtemplate'),
        ),
        migrations.AddField(
            model_name='scoringrule',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scoring_rules', to='users.organization'),
        ),
        migrations.AddField(
            model_name='segment',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='users.organization'),
        ),
        migrations.AddField(
            model_name='segment',
            name='static_contacts',
            field=models.ManyToManyField(blank=True, related_name='static_segments', to='email_crm.contact'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='segment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='email_crm.segment'),
        ),
        migrations.AddField(
            model_name='smscampaign',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_campaigns', to='users.organization'),
        ),
        migrations.AddField(
            model_name='smscampaign',
            name='segment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='email_crm.segment'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['org', 'lead_score'], name='contacts_org_id_878004_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['org', 'source'], name='contacts_org_id_363304_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together={('org', 'email')},
        ),
        migrations.AddIndex(
            model_name='campaignevent',
            index=models.Index(fields=['campaign', 'event_type'], name='campaign_ev_campaig_210bca_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='automationenrollment',
            unique_together={('automation', 'contact')},
        ),
        migrations.AddIndex(
            model_name='contactactivity',
            index=models.Index(fields=['contact', '-created_at'], name='contact_act_contact_827c2f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='deliverabilitymetrics',
            unique_together={('org', 'date')},
        ),
    ]
