import Link from "next/link";
import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Terms of Service — AgentBloom",
    description: "AgentBloom Terms of Service",
};

export default function TermsPage() {
    return (
        <main className="min-h-screen bg-white dark:bg-gray-950">
            <div className="max-w-3xl mx-auto px-6 py-16">
                <Link href="/" className="text-blue-600 hover:underline text-sm mb-8 inline-block">
                    ← Back to AgentBloom
                </Link>
                <h1 className="text-4xl font-bold mb-2">Terms of Service</h1>
                <p className="text-gray-500 mb-10">Last updated: February 24, 2026</p>

                <div className="prose dark:prose-invert max-w-none space-y-6">
                    <section>
                        <h2 className="text-2xl font-semibold mt-8 mb-3">1. Acceptance of Terms</h2>
                        <p>By accessing or using AgentBloom (&quot;the Service&quot;), operated by NobleBlocks LLC (&quot;we&quot;, &quot;us&quot;, &quot;our&quot;), you agree to be bound by these Terms of Service. If you do not agree, do not use the Service.</p>
                    </section>

                    <section>
                        <h2 className="text-2xl font-semibold mt-8 mb-3">2. Description of Service</h2>
                        <p>AgentBloom is an AI-powered business platform that provides website building, email marketing, CRM, course creation, calendar booking, payment processing, SEO tools, knowledge base management, and AI receptionist capabilities.</p>
                    </section>

                    <section>
                        <h2 className="text-2xl font-semibold mt-8 mb-3">3. Account Registration</h2>
                        <p>You must provide accurate and complete information when creating an account. You are responsible for maintaining the security of your account credentials. You must be at least 18 years old to use the Service.</p>
                    </section>

                    <section>
                        <h2 className="text-2xl font-semibold mt-8 mb-3">4. Acceptable Use</h2>
                        <p>You agree not to:</p>
                        <ul className="list-disc pl-6 space-y-1">
                            <li>Use the Service for any illegal or unauthorized purpose</li>
                            <li>Violate any laws or regulations in your jurisdiction</li>
                            <li>Send spam, unsolicited emails, or abusive content</li>
                            <li>Attempt to gain unauthorized access to any part of the Service</li>
                            <li>Upload malicious code, viruses, or harmful content</li>
                            <li>Infringe on intellectual property rights of others</li>
                            <li>Use the AI features to generate harmful, deceptive, or illegal content</li>
                        </ul>
                    </section>

                    <section>
                        <h2 className="text-2xl font-semibold mt-8 mb-3">5. Payment Terms</h2>
                        <p>Paid features are billed in advance on a monthly or annual basis. All fees are non-refundable except as required by law. We reserve the right to change pricing with 30 days&apos; notice. Payment processing is handled by Stripe.</p>
                    </section>

                    <section>
                        <h2 className="text-2xl font-semibold mt-8 mb-3">6. Intellectual Property</h2>
                        <p>You retain ownership of content you create using the Service. We retain ownership of the Service, its design, code, and underlying technology. You grant us a limited license to host and display your content as necessary to provide the Service.</p>
                    </section>

                    <section>
                        <h2 className="text-2xl font-semibold mt-8 mb-3">7. AI-Generated Content</h2>
                        <p>Content generated by our AI features is provided &quot;as-is.&quot; You are responsible for reviewing and approving all AI-generated content before publishing. We do not guarantee the accuracy, completeness, or appropriateness of AI-generated content.</p>
                    </section>

                    <section>
                        <h2 className="text-2xl font-semibold mt-8 mb-3">8. Data and Privacy</h2>
                        <p>Your use of the Service is also governed by our <Link href="/privacy" className="text-blue-600 hover:underline">Privacy Policy</Link>. We process data in accordance with applicable data protection laws.</p>
                    </section>

                    <section>
                        <h2 className="text-2xl font-semibold mt-8 mb-3">9. Service Availability</h2>
                        <p>We strive for high availability but do not guarantee uninterrupted access. We may perform maintenance, updates, or modifications that temporarily affect availability. We are not liable for any downtime or data loss.</p>
                    </section>

                    <section>
                        <h2 className="text-2xl font-semibold mt-8 mb-3">10. Limitation of Liability</h2>
                        <p>TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SERVICE IS PROVIDED &quot;AS IS&quot; WITHOUT WARRANTIES OF ANY KIND. WE SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES ARISING FROM YOUR USE OF THE SERVICE.</p>
                    </section>

                    <section>
                        <h2 className="text-2xl font-semibold mt-8 mb-3">11. Termination</h2>
                        <p>We may suspend or terminate your account at any time for violation of these Terms. You may cancel your account at any time. Upon termination, your right to use the Service ceases immediately. We will provide data export options where technically feasible.</p>
                    </section>

                    <section>
                        <h2 className="text-2xl font-semibold mt-8 mb-3">12. Changes to Terms</h2>
                        <p>We may update these Terms at any time. Material changes will be communicated via email or in-app notification. Continued use of the Service after changes constitutes acceptance of the updated Terms.</p>
                    </section>

                    <section>
                        <h2 className="text-2xl font-semibold mt-8 mb-3">13. Contact</h2>
                        <p>For questions about these Terms, contact us at <a href="mailto:legal@nobleblocks.com" className="text-blue-600 hover:underline">legal@nobleblocks.com</a>.</p>
                    </section>
                </div>
            </div>
        </main>
    );
}
