# Generated by Django 5.1.15 on 2026-02-24 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutpage',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkout_pages', to='users.organization'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='users.organization'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='users.organization'),
        ),
        migrations.AddField(
            model_name='orderbump',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_bumps', to='users.organization'),
        ),
        migrations.AddField(
            model_name='payment',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='users.organization'),
        ),
        migrations.AddField(
            model_name='platformsubscription',
            name='org',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='platform_subscription', to='users.organization'),
        ),
        migrations.AddField(
            model_name='platformsubscription',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.platformplan'),
        ),
        migrations.AddField(
            model_name='orderbump',
            name='bump_price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.price'),
        ),
        migrations.AddField(
            model_name='checkoutpage',
            name='price',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.price'),
        ),
        migrations.AddField(
            model_name='product',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='users.organization'),
        ),
        migrations.AddField(
            model_name='price',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='payments.product'),
        ),
        migrations.AddField(
            model_name='orderbump',
            name='bump_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bump_offers', to='payments.product'),
        ),
        migrations.AddField(
            model_name='orderbump',
            name='trigger_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bumps_triggered', to='payments.product'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='applies_to_products',
            field=models.ManyToManyField(blank=True, related_name='coupons', to='payments.product'),
        ),
        migrations.AddField(
            model_name='checkoutpage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkout_pages', to='payments.product'),
        ),
        migrations.AddField(
            model_name='refund',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='refund',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='payments.payment'),
        ),
        migrations.AddField(
            model_name='revenuesnapshot',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenue_snapshots', to='users.organization'),
        ),
        migrations.AddField(
            model_name='stripeconnection',
            name='org',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stripe_connection', to='users.organization'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='users.organization'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='price',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.price'),
        ),
        migrations.AddField(
            model_name='taxrule',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_rules', to='users.organization'),
        ),
        migrations.AddField(
            model_name='usagetracking',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage', to='users.organization'),
        ),
        migrations.AlterUniqueTogether(
            name='coupon',
            unique_together={('org', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='checkoutpage',
            unique_together={('org', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='revenuesnapshot',
            unique_together={('org', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='usagetracking',
            unique_together={('org', 'metric', 'period')},
        ),
    ]
