# Generated by Django 5.1.15 on 2026-02-24 11:19

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service', models.CharField(choices=[('search_console', 'Search Console'), ('analytics', 'Google Analytics')], max_length=50)),
                ('property_url', models.URLField(blank=True)),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('token_expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'google_connections',
            },
        ),
        migrations.CreateModel(
            name='InternalLinkSuggestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('anchor_text', models.CharField(max_length=255)),
                ('context', models.TextField(blank=True)),
                ('confidence', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('suggested', 'Suggested'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='suggested', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'internal_link_suggestions',
                'ordering': ['-confidence'],
            },
        ),
        migrations.CreateModel(
            name='PageSpeedMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lcp', models.FloatField(blank=True, null=True)),
                ('fid', models.FloatField(blank=True, null=True)),
                ('cls', models.FloatField(blank=True, null=True)),
                ('inp', models.FloatField(blank=True, null=True)),
                ('ttfb', models.FloatField(blank=True, null=True)),
                ('performance_score', models.IntegerField(blank=True, null=True)),
                ('seo_score', models.IntegerField(blank=True, null=True)),
                ('accessibility_score', models.IntegerField(blank=True, null=True)),
                ('best_practices_score', models.IntegerField(blank=True, null=True)),
                ('total_size_kb', models.IntegerField(default=0)),
                ('image_size_kb', models.IntegerField(default=0)),
                ('js_size_kb', models.IntegerField(default=0)),
                ('css_size_kb', models.IntegerField(default=0)),
                ('measured_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'page_speed_metrics',
                'ordering': ['-measured_at'],
            },
        ),
        migrations.CreateModel(
            name='SEOAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.IntegerField(default=0)),
                ('issues', models.JSONField(default=list)),
                ('recommendations', models.JSONField(default=list)),
                ('page_scores', models.JSONField(default=dict)),
                ('technical_score', models.IntegerField(default=0)),
                ('content_score', models.IntegerField(default=0)),
                ('performance_score', models.IntegerField(default=0)),
                ('accessibility_score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'seo_audits',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SEOSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auto_seo_enabled', models.BooleanField(default=True)),
                ('schema_markup_enabled', models.BooleanField(default=True)),
                ('schema_types', models.JSONField(blank=True, default=list)),
                ('sitemap_enabled', models.BooleanField(default=True)),
                ('sitemap_url', models.URLField(blank=True)),
                ('sitemap_last_generated', models.DateTimeField(blank=True, null=True)),
                ('robots_txt', models.TextField(blank=True, default='User-agent: *\nAllow: /')),
                ('google_analytics_id', models.CharField(blank=True, max_length=100)),
                ('google_search_console_verified', models.BooleanField(default=False)),
                ('local_seo_enabled', models.BooleanField(default=False)),
                ('business_name', models.CharField(blank=True, max_length=255)),
                ('business_address', models.JSONField(blank=True, default=dict)),
                ('business_phone', models.CharField(blank=True, max_length=50)),
                ('business_hours', models.JSONField(blank=True, default=dict)),
                ('service_area', models.JSONField(blank=True, default=list)),
                ('ai_search_optimization', models.BooleanField(default=True)),
                ('entity_markup_enabled', models.BooleanField(default=True)),
                ('auto_image_optimization', models.BooleanField(default=True)),
                ('lazy_loading_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SEO Settings',
                'verbose_name_plural': 'SEO Settings',
                'db_table': 'seo_settings',
            },
        ),
        migrations.CreateModel(
            name='TrackedKeyword',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('keyword', models.CharField(max_length=255)),
                ('current_rank', models.IntegerField(blank=True, null=True)),
                ('previous_rank', models.IntegerField(blank=True, null=True)),
                ('best_rank', models.IntegerField(blank=True, null=True)),
                ('search_volume', models.IntegerField(blank=True, null=True)),
                ('difficulty', models.IntegerField(blank=True, null=True)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('history', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'tracked_keywords',
            },
        ),
    ]
