# Generated by Django 5.1.15 on 2026-02-24 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seo', '0001_initial'),
        ('site_builder', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='googleconnection',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='google_connections', to='users.organization'),
        ),
        migrations.AddField(
            model_name='internallinksuggestion',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_suggestions', to='site_builder.site'),
        ),
        migrations.AddField(
            model_name='internallinksuggestion',
            name='source_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbound_suggestions', to='site_builder.page'),
        ),
        migrations.AddField(
            model_name='internallinksuggestion',
            name='target_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbound_suggestions', to='site_builder.page'),
        ),
        migrations.AddField(
            model_name='pagespeedmetrics',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speed_metrics', to='site_builder.page'),
        ),
        migrations.AddField(
            model_name='seoaudit',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seo_audits', to='site_builder.site'),
        ),
        migrations.AddField(
            model_name='seosettings',
            name='site',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seo_settings', to='site_builder.site'),
        ),
        migrations.AddField(
            model_name='trackedkeyword',
            name='ranking_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='site_builder.page'),
        ),
        migrations.AddField(
            model_name='trackedkeyword',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracked_keywords', to='site_builder.site'),
        ),
        migrations.AlterUniqueTogether(
            name='trackedkeyword',
            unique_together={('site', 'keyword')},
        ),
    ]
